### PR TITLE
Prevent incorrect user_not_volume_owner messages

### PR DESCRIPTION
**Pull request by cvgs**
Prevent incorrect user_not_volume_owner messages by checking RealName and all RecordName attributes with case insensitivity

Sometimes erase-install incorrectly shows that the user is not volume owner, because the account_shortname can be different from the name that is returned by fdesetup list.

There are three main reasons:
- The end user enters the username in a different capitalization, and we to a case-sensitive comparison
- The end user enters his RealName, or a different RecordName belonging to his user account (as the user record can have multiple RecordNames)
- --currentUser returns a different RecordName than what is stored in "fdesetup list". Not sure why, but i have seen this happen as well (like John.Doe vs. John.Doe@pretendco.com)

This pull request expands the volume owner comparison as follows:

- do a case-insensitive match
- compare all RecordNames against the account_shortname
- compare the RealName against the account_shortname

This should cover the cases listed above so that the volume owner check should return a valid result, regardless of the entered account_shortname.

### CODE REVIEW

**Comment by grahampugh** [comment]
Changing this to merge into `v25.1-rc` branch, which is ahead of `main`.

**Comment by grahampugh** [comment]
I have built new packages including this change into the 25.1 pre-release. Please can you try it out?

**Comment by cvgs** [comment]
I am trying the 25.1rc right now, but i keep getting reproducable errors in the caching stage that say "Build 21C52 selected. Downloading #18...   [run_installinstallmacos] Error obtaining valid installer. Cannot continue.".

I've tested it multiple times now, and "erase-install --move --update" always fails here. Running installinstallmacos by hand works, as well as running the curl command shown in the eraseinstall.log, so i guess it's not a problem with my internet connection. Tested on MacBookPro17,1 and MacBookPro14,1.
 
Just wanted to give feedback so you can double-check that.
[erase-install.log](https://github.com/grahampugh/erase-install/files/7761226/erase-install.log)

Will report on the user feature once i've cached an installer manually…

**Comment by cvgs** [comment]
Apart from the download problems, 25.1rc worked for upgrading from Big Sur to Monterey, and it correctly parsed the volume owner.

**Pull request merged**
