### PR TITLE
Allow Jamf Pro to receive the log results of erase-install after running startosinstall 

### PR DESCRIPTION
**Pull request by cvgs**
In its current form, erase-install does not send its log output or result code back to Jamf Pro when upgrading the OS. It also cannot be called using the "Scripts" section of a Jamf Pro policy, because then the restart is being blocked.

The reason for this is twofold:
- the Jamf policy is still active when startosinstall tries to reboot the machine. The Jamf agent will be killed and is not able to gather and upload the result of the erase-install script
- when started from the Scripts section, startosinstall apparently cannot terminate the Jamf agent, because the Jamf agent is waiting for startosinstall to quit before continuing. Thus the restarting process will be blocked until the user manually reboots the machine (then the actual installation will be done)

There is a mechanism to send USR1 signal to startosinstall and its calling process, but that is only useful for reducing the rebootdelay; it does not fix the deadlock situation with Jamf.

To allow policy logs to be returned to Jamf Pro, we must allow the Jamf agent to properly quit before startosinstall takes over and reboots the machine. To make matters more complicated, it is not sufficient to launch startosinstall as a background process of erase-install (because the Jamf agent will still wait until all its child processes are terminated before continuing). We must run startosinstall as a completely independent process (using launchctl); but we still need to pass the user's password securely to the startosinstall process.

Also, it is imperative to set a rebootdelay so that the Jamf agent has enough time to complete its reporting back to the Jamf Pro server. Otherwise the behaviour will be unchanged and the policy run will not be recorded in Jamf Pro.

This Pull Request implements the launching of startosinstall as an independent process instead of launching a background child process, which allows erase-install to be launched in the traditional Jamf Pro way by calling it from the scripts section. Jamf Pro will then record the progress log and the return code of the script; this will allow Jamf Pro to display the policy as either successful or failed.

As the preferred method of running erase-install is now to deploy the PKG, this pull request also includes a launcher script which can be added to Jamf Pro. This will simply pass all arguments to the erase-install script at /Library/Management/erase-install and return its exit code back to Jamf Pro.

Because of the redesign of the launch mechanism, the --test-run mode was expanded as well.

Technical Details:

1. Create two random pipes in a non-deterministic location for securely communicating with the independent process

2. Create a launchd.plist in this tmpdir with all arguments for startosinstall, and
2.1. StandardInPath = path to our first pipe
2.2. StandardOutPath = path to our second pipe
2.3. Set proper permissions, load this launchdaemon and remove the launchd.plist

3.   startosinstall is running now.
3.1. If we are on Apple Silicon we need to send account_password through the first pipe to startosinstall
3.2. so we need to copy the contents of the second pipe (StandardOutPath) to our own stdout, so that it appears im the erase-install.log

4.  startosinstall completed its work.
4.1 startosinstall is ready to reboot, signals USR1 and then waits for rebootdelay. We get interrupted and exit as soon as possible through post_prep_work, giving the Jamf agent a chance to upload its policy log.
4.2 startosinstall is ready to reboot, signals USR1 and immediately reboots the machine because it either is too old to support rebootdelay or the delay is set to 0. We get interrupted and try to exit, but the machine will be forcibly rebooted and the Jamf agent does not have a chance to upload its policy log. This is the current behaviour)
4.3 startosinstall quits for some other reason and closes StandardOutPath (the second pipe). The read command quits, we continue and exit with an error code (because startosinstall was supposed to send us USR1 signal).
4.4 startosinstall crashes, and does not close StandardOutPath. Our read loop never finishes and we would hang forever. So we have a backup mechanism which will timeout after 1h, then we exit with error code.

I have tested this modification successfully with --erase and --upgrade on Intel (macOS 10.15 and macOS 12) and M1 (macOS 11 and macOS 12) and it worked in my scenarios, so i'm hopeful that i did not break previous functionality.

### CODE REVIEW

**Comment by grahampugh** [comment]
Nobody else reported to me that the restart was failing if the script is uploaded to Jamf. How did you test that? Admittedly we haven't tested it that way for a while, but it was the original way I deployed the script and it worked back then :)

This PR is a big change and has some benefit, but the new dependence on a second launcher script is problematic. I fear it will not work in some scenarios that are commonly used, such as uploading the script directly to Jamf or other MDM, or the curl to bash option (This tool is not only used by Jamf users).

Such a breaking change has other implications - if there's no way to run the script without deploying the package then there are various other things that may as well be removed from the script, such as downloading python3 or installinstallmacos.py if missing. Why even keep it as one big script at all if it has to be deployed by the package? Lots to think about. 

I will need to consider whether those breaking changes are worth the benefit of seeing the logs in Jamf after a successful upgrade or erase (logs are already shipped if the process fails). Or maybe there is a smaller amount of changes that could achieve the same thing without needing the separate script.

**Comment by cvgs** [comment]
The script blocking restart was just something i noticed when trying to get log results back for successful runs. I did not aggressively verify the issue, but it seemed consistent.

Just one thing: the launcher script is not strictly necessary. You can still start erase-install in the traditional way by installing the pkg and using the "Files and Processes" section to start it, or include erase-install.sh in Jamf Pro and launch it from the Scripts section as before, or even launch it directly from Terminal.app; the change should be fully backwards compatible.

The launcher script is just beneficial when using the pkg, as it allows more parameters for erase-install, and makes it easy to start erase-install from the Scripts section. Otherwise it’s totally optional.

But yes, this is a major rework of the startosinstall part of the script, so it should be verified thoroughly.

**Comment by grahampugh** [comment]
Thanks for the clarification. I'll certainly give it consideration. I'll create a new dev branch over the next few days and merge it in and give it a try.

**Comment by grahampugh** [comment]
I'm still not seeing the point of the additional launcher script over just using the Run Command. It just seems to be adding unnecessary complexity to add a script. Nothing to stop anyone making their own of course, but I don't really see that it makes it any easier for anyone. Therefore I'm not seeing the need for it to be in this repo and have to explain yet another option for running the script in the wiki. Unless you are aware of some kind of command length limit in Run Command that I'm not aware of?

**Comment by grahampugh** [comment]
Another question, have you tried running this with both `--depnotify` mode and without, and on a device that does not have Jamf on it with both `--depnotify` mode and without? I haven't yet dug deep enough into your code changes to assume that this would be OK - I just want to ask the question because your changes are very much focused on Jamf but there are many users of this script who are not Jamf users.

**Comment by grahampugh** [comment]
Hmm that is a valid difference. So you're saying that even with all the changes you made, the policy will still return success if it fails when run from Run Command? 

(Sorry for asking all the questions but I don't have much testing time available at present)

**Comment by cvgs** [comment]
That's correct. With my changes the log results are always being properly returned to Jamf Pro (however, for best results a rebootdelay should be set to give the jamf process enough time to upload its results). So thats an improvement in itself.

But the success/failure state is only reflected in the policy if the erase-install has been launched through the Scripts section; with the "Execute Command" method the return code of the script is ignored. Which in turn means you either need to copy erase-install.sh into Jamf Pro (in addition to deploying the pkg or a Python version), or you need to use erase-install-launcher (which should be fairly static).

And no worries, don't hesitate to ask more questions!

**Comment by grahampugh** [comment]
Merging into branch v27.0-rc for testing.

**Pull request merged**
