### PR TITLE
DEPNotify Progress Bar

### PR DESCRIPTION
**Pull request by andredb90**
Use a background process to determine the `startoinstall` progress while moving the DEPNotify bar accordingly.

Providing a better feedback for the users while macOS installation is being prepared.

### CODE REVIEW

**Comment by grahampugh** [comment]
Please could you test this out in the 0.22.0 pre-release?

**Comment by andredb90** [comment]
- Works as expected for `--erase --depnotify`, `--reinstall --depnotify` 
- Resets properly after cancel/re-run  

FYI: Likely unrelated to the progressbar changes but I'm hitting an issue with the DEPNotify confirmation button, which falsely  declines instead of confirms after pressing it.

**Comment by grahampugh** [comment]
Thanks, I'll look at that. I did make some changes to the confirmation dialog to address a request to allow it for reinstalls. I probably messed something up.

**Comment by grahampugh** [comment]
Hmm, strange, the confirmation button is working as expected for me.

**Comment by grahampugh** [comment]
I'm trying out the progress bar for the first time. This is awesome! Thanks for this.
Interestingly, it got to 33% on a Catalina box, and then it rebooted (or at least went to the Apple start screen). I guess that is how it rolls on Catalina, and they moved the prep phase more to pre-restart on Big Sur.

It might be a rabbit hole, but now I'm wondering if something similar can be done for a progress bar while downloading.It's a long standing FR, maybe it's possible to read the output of `installinstallmacos.py` and/or `softwareupdate --fetch-full-installer`...

**Comment by andredb90** [comment]
Re: Confirmation button
I assume there was something odd on my test machine then. Now working as expected on a fresh installed macOS.

Re: Progress bar: 
Glad to hear, thank you!
I noticed the same behaviour on macOS 10.14 and 10.15. Preparing goes up to 100 (or above) for macOS 11 and and also 12 (so far at least).I guess one could increase the steps for the bar when upgrading from an older OS than 11. I'm not sure if it's worth changing it though. The main purpose was to give the user some feedback, which is given as long as it's moving, restarting, installing.

Re: Download
I thought the same and already starting to look into this. I'll definitely let you know once I've got a working solution. Maybe displaying the version which is being downloaded would be nice and a similar working progress bar. - Haven't had the time to test it more though.

**Comment by grahampugh** [comment]
Sounds awesome! Glad you're also curious about that! 

I agree, not worth solving for <=10.15, that's a problem that goes away in time :)

**Pull request merged**
