### PR TITLE
Add log rotation

### PR DESCRIPTION
**Pull request by aschwanb**
Log files are saved to a dedicated directory. However, they’re currently overwritten every time the program is executed. 

This PR adds a simple log rotating function.

### CODE REVIEW

**Comment by grahampugh** [comment]
In real life usage, why would we need to keep a log history?

**Comment by aschwanb** [comment]
Thanks for your fast reply. A few use cases come to mind. Eg.

* Issues when trying to download the OS installer
* Interaction with mist/swiftDialog
* Having a better understanding about the update procedure in general.
    * User Updated and ended up with the “wrong” version of the OS. By keeping the logs we can see if the update was triggered by erase-install or not.
    * User claiming repeated issues when updating with erase-install. By keeping the logs we can get a clearer picture about the situation


I realize that most of these are factors outside of the direct control of erase-install. However, I think having the log history available will help people to better understand what’s going on and identify the underlying issues more quickly.

**Comment by grahampugh** [comment]
To be honest, I'm still not really seeing a use case where anything other than the _latest_ log would be useful. But, I guess it would be relatively harmless to add. 

However, I don't like that the old log files would be named `erase-install.log.1` etc., because the file extension is important. Can you alter the code so that the old log files become `erase-install.1.log` etc?

Also, it should be unnecessary to use: `i=$(( $i - 1 ))`. `((i--))` should suffice.

**Comment by grahampugh** [comment]
Oh, yes, it does look like log.* is interpreted properly by Finder. Fair enough, then you can leave it as is.

**Pull request merged**
